/* Auto-generated by genmsg_cpp for file /home/ulrich/ros_workspace/follow_line/msg/LinePos.msg */
#ifndef FOLLOW_LINE_MESSAGE_LINEPOS_H
#define FOLLOW_LINE_MESSAGE_LINEPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace follow_line
{
template <class ContainerAllocator>
struct LinePos_ {
  typedef LinePos_<ContainerAllocator> Type;

  LinePos_()
  : x(0.0)
  , y(0.0)
  , angle(0.0)
  {
  }

  LinePos_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , angle(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _angle_type;
  double angle;


private:
  static const char* __s_getDataType_() { return "follow_line/LinePos"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "57832a67d2f8a00310788a06c92c59b2"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 x\n\
float64 y\n\
float64 angle\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(angle);
    return size;
  }

  typedef boost::shared_ptr< ::follow_line::LinePos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::follow_line::LinePos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LinePos
typedef  ::follow_line::LinePos_<std::allocator<void> > LinePos;

typedef boost::shared_ptr< ::follow_line::LinePos> LinePosPtr;
typedef boost::shared_ptr< ::follow_line::LinePos const> LinePosConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::follow_line::LinePos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::follow_line::LinePos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace follow_line

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::follow_line::LinePos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::follow_line::LinePos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::follow_line::LinePos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "57832a67d2f8a00310788a06c92c59b2";
  }

  static const char* value(const  ::follow_line::LinePos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x57832a67d2f8a003ULL;
  static const uint64_t static_value2 = 0x10788a06c92c59b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::follow_line::LinePos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "follow_line/LinePos";
  }

  static const char* value(const  ::follow_line::LinePos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::follow_line::LinePos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 angle\n\
\n\
";
  }

  static const char* value(const  ::follow_line::LinePos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::follow_line::LinePos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::follow_line::LinePos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LinePos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::follow_line::LinePos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::follow_line::LinePos_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FOLLOW_LINE_MESSAGE_LINEPOS_H

